### ISSUE TITLE
Send vrs identifiers to  metakb service for evidence

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/vrs_anvil_toolkit#3]
The example notebooks had two methods:
- decorate(vrs_decorator, vrs_objects, limit)
- def meta_kb(item: tuple)

Write a command line utility to take the results of vrs normalization, call meta_kb, log any 'hits', track the ratio of hits to misses, measure throughput.

We will need to coordinate with the Wagner Lab who will maintain the meta_kb instance for our testing.

Write integration tests to verify
ie
tests/integration/YOUR-TEST-HERE.py

These tests should not be in tests/unit

**Comment by bwalsh** [comment]
See https://github.com/ohsu-comp-bio/vrs-python-testing/blob/d088ef23fab9c73fcba5d84c646179be9f551ba8/vrs_anvil/__init__.py#L177-L208
for the start of the metaKB cache

**Comment by quinnwai** [comment]
started by Walsh in #43 with pytest and some requirements referenced in #37. Actual querying of metakb will come once the new metakb API is setup with the new digests from vrs-python 2.0.0a5

**Comment by quinnwai** [comment]
This will be done ~March 25 when there is a new API to hit with updated vrs-python 2.0.0a5 digests

**Comment by bwalsh** [comment]
@quinnwai noticed the merge, is this issue still active? close if appropriate.

**Comment by quinnwai** [comment]
Agreed, closing as this has been addressed
